// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mocks/mock_ports.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/z-alamsyah/codebase-go/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockWelcomeSender is a mock of WelcomeSender interface.
type MockWelcomeSender struct {
	ctrl     *gomock.Controller
	recorder *MockWelcomeSenderMockRecorder
	isgomock struct{}
}

// MockWelcomeSenderMockRecorder is the mock recorder for MockWelcomeSender.
type MockWelcomeSenderMockRecorder struct {
	mock *MockWelcomeSender
}

// NewMockWelcomeSender creates a new mock instance.
func NewMockWelcomeSender(ctrl *gomock.Controller) *MockWelcomeSender {
	mock := &MockWelcomeSender{ctrl: ctrl}
	mock.recorder = &MockWelcomeSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWelcomeSender) EXPECT() *MockWelcomeSenderMockRecorder {
	return m.recorder
}

// SendWelcomeEmail mocks base method.
func (m *MockWelcomeSender) SendWelcomeEmail(ctx context.Context, ev model.UserCreatedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendWelcomeEmail", ctx, ev)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendWelcomeEmail indicates an expected call of SendWelcomeEmail.
func (mr *MockWelcomeSenderMockRecorder) SendWelcomeEmail(ctx, ev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWelcomeEmail", reflect.TypeOf((*MockWelcomeSender)(nil).SendWelcomeEmail), ctx, ev)
}
